FROM postgres:17.6-alpine

# PostgreSQL seulement maintenant
# PgBouncer déplacé dans son propre conteneur Alpine

# Exposition du port PostgreSQL uniquement
EXPOSE 5432

# Démarrage PostgreSQL standard
CMD ["postgres"]