services:
  redis:
    image: redis:7.4-alpine
    container_name: ${REDIS_CONTAINER_NAME:-cinephoria.redis}
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ../../../docker-volumes/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - ecf_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    command: >
      redis-server /usr/local/etc/redis/redis.conf
      --requirepass ${REDIS_PASSWORD}
